spring:
  application:
  name : ec2-test-app

  thymeleaf:
    cache: false  # 운영단계에서는 true(기본값), 개발단계에서는 false -> HTML 변경사항이 즉각 반영
    prefix: classpath:/templates/   # 기본값. 템플릿 파일 위치
    suffix: .html   # 기본값. 확장자
    encoding: UTF-8   # 기본값. 한글 깨짐 방지

  jackson:  # JSON 변환 라이브러리 타임
    level:
      root: INFO  # 전체 애플리케이션 로그 레벨 (ERROR, WARN, INFO, DEBUG, TRACE)
      com.example.ec2testapp: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080
